[package]
authors = ["FL03 <jo3mccain@icloud.com"]
categories = []
description = "conduit"
edition = "2021"
keywords = []
license = "MIT"
name = "conduit"
version = "0.1.0"


[build-dependencies]

[dependencies]
scsys = { features = ["full"], version = "0.1.24" }
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.87"

[dev-dependencies]
