[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "contained is a research project implementing the proposed harmonic runtime for orchestrating cloud-native systems"
edition = "2021"
homepage = "https://github.com/FL03/contained/wiki"
keywords = []
license = "Apache-2.0"
name = "contained"
repository = "https://github.com/FL03/contained"
version = "0.1.2"

[[bin]]
bench = false
name = "contained"
path = "src/main.rs"
test = true

[build-dependencies]

[dev-dependencies]

[dependencies]
acme = { features = ["net"], git = "https://github.com/FL03/acme", branch = "v0.2.5", version = "0.2.5" }
async-trait = "0.1"
axum = { features = ["headers", "http2", "macros"], version = "0.6" }
clap = { features = ["cargo", "derive", "env"], version = "4" }
futures = "0.3"
http = "0.2"
hyper = { features = [], version = "0.14" }
scsys = { features = [], version = "0.1.40" }
serde = { features = ["derive"], version = "1" }
serde_json = "1"
smart-default = "0.6.0"
strum = { features = ["derive"], version = "0.24.1" }
tokio = { features = ["full"], version = "1.23.0" }
tower = "0.4.13"
tower-http = { features = ["full"], version = "0.3.5" }
tracing = "0.1.37"
tracing-subscriber = { features = ["env-filter"], version = "0.3.16" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
