mode = "development"

[cache]
database = 0
host = "localhost"
password = ""
port = 6379
username = ""


[database] # Standard database connection parameters
database = "postgres"
enabled = true
host = "localhost"
provider = "postgres"
port = 5432

[logger]
level = "info"

[network]

[network.mainnet]

[network.subnet]
addr = "/ip4/0.0.0.0/tcp/9001"
seed = 9

[system]
