# This workflow is used to benchmark a Rust project
name: cargo-test
# The workflow may be manually triggered and is run automatically when:
# - a pull request is closed on the default branch (main/master)
# - a release is published
# - a repository_dispatch event with the type "cargo-test" is received

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  repository_dispatch:
    types: [cargo-test]
  workflow_dispatch:
    inputs:
      toolchain:
        description: 'Rust toolchain to use (stable, beta, nightly, or a specific version)'
        required: false
        default: 'stable'
        type: choice
        options: [ stable, nightly, beta]

        
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: Cargo Test
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: ${{ github.event.inputs.toolchain || 'stable' }}
    outputs:
      status: ${{ steps.test.outputs.status }}
    strategy:
      fail-fast: false
      matrix:
        features: [full]
        packages: [workspace]
        target: [x86_64-unknown-linux-gnu]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.ref || github.ref }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
      - name: Test workspace (${{ matrix.target }})
        id: test
        if: matrix.packages == 'workspace' || matrix.packages == 'all'
        run: cargo test --locked --verbose --workspace \
          --features ${{ matrix.features }} \
          --target ${{ matrix.target }}
      - name: "Test ${{ matrix.packages }}:${{ matrix.target }}"
        id: test-package
        if: matrix.packages != 'workspace'
        run: cargo test --locked --verbose -p ${{ matrix.packages }} \
          --features ${{ matrix.features }} \
          --target ${{ matrix.target }}