name: Docker

on:
  pull_request:
    branches-ignore: [ "dev*", "next", "nightly*" ]
  push:
    branches-ignore: [ "dev*", "next", "nightly*" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 21 * * *" # 9:30 UTC
  workflow_dispatch:

env:
  REGISTRY: hub.docker.com
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: buildx
        run: docker buildx build --tag ${{ secrets.DOCKERHUB_USERNAME }}/contained:latest .
      - name: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.sha }}
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        path: /tmp/.buildx-cache
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        dockerfile: Dockerfile
        name: ${{ secrets.DOCKERHUB_USERNAME }}/contained
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        snapshot: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
