name: Nightly

env:
  CARGO_TERM_COLOR: always

on:
  schedule:
    - cron: "30 21 * * *" # 9:30pm UTC

jobs:
  rust:
    name: Rust
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [nightly, stable]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup langspace
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt install -y protobuf-compiler
          rustup default ${{ matrix.toolchain }}
      - name: Build (workspace)
        run: cargo build --release -v --workspace
      - name: Bench (workspace)
        run: cargo bench -v --workspace
      - name: Test (all)
        run: cargo test --all --all-features -v
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/release/contained
          draft: true
          prerelease: true
