name: Nightly

env:
  CARGO_TERM_COLOR: always

on:
  schedule:
    - cron: "30 21 * * *" # 9:30pm UTC
  workflow_dispatch:

jobs:
  build:
    name: Builder
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [nightly, stable]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: setup (ubuntu)
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt install -y protobuf-compiler
      - name: langspace
        run: rustup default ${{ matrix.toolchain }}
      - name: build
        run: cargo build -r -v --workspace
      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          files: |
            target/release/contained
          name: ${{ github.repository }}-nightly
          prerelease: true
