name: Nightly

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ "nightly*" ]
    tags: [ "nightly*" ]
  push:
    branches: [ "nightly*" ]
    tags: [ "nightly*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: setup langspace
        run: rustup default ${{ matrix.toolchain }}
      - run: cargo build --workspace
      - run: cargo test --all --all-features -v
