name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ "main", "master", "prod" ]
    tags: [ "v*.*.*" ]
  push:
    branches: [ "main", "master", "prod" ]
    tags: [ "v*.*.*" ]
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: setup langspace
        run: rustup default ${{ matrix.toolchain }}
      - run: cargo build --workspace
      - run: cargo test --all --all-features -v
  publish:
    if: ${{ github.event.inputs.publish == true }}
    name: Publish
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish (contained)
        run: cargo publish --all-features -v -p contained --token ${{ secrets.CARGO_REGISTRY_TOKEN }}