name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches-ignore: [ "beta*", "dev*", "next*" ]
    tags: [ "nightly*",  "v*.*.*" ]
  release:
  repository_dispatch:
    types: [ "publish" ]
  schedule:
    - cron: "30 9 * * 5" # Every Friday at 9:30am UTC
  workflow_dispatch:
    inputs:
      benchmark:
        default: false
        description: 'Benchmark'
        required: true
        type: boolean

jobs:
  build:
    name: Builder
    strategy:
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup (langspace)
        run: |
          rustup update
      - name: Build
        run: cargo build -F full --release -v --workspace
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup (langspace)
        run: |
          rustup update
      - name: Test
        run: cargo test --all -F full --release -v
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup (langspace)
        run: |
          rustup update
          rustup default nightly
      - name: Bench
        run: cargo bench --all -v