name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches-ignore: [ "dev*" ]
  push:
    branches-ignore: [ "dev*" ]
    tags: [ "v*.*.*" ]
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: setup langspace
        run: |
          sudo apt install -y protobuf-compiler
          rustup default ${{ matrix.toolchain }}
      - run: cargo build --workspace
      - run: cargo test --all --all-features -v
  features:
    if: ${{ github.event.inputs.publish }}
    name: Features
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: 
          - contained-core
          - contained-music
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y protobuf-compiler
      - name: Publish (${{ matrix.pkg }})
        run: cargo publish --all-features -v -p ${{ matrix.pkg }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    if: ${{ github.event.inputs.publish }}
    name: Publish
    needs: [ build, features ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y protobuf-compiler
      - name: Publish (contained)
        run: cargo publish --all-features -v -p contained --token ${{ secrets.CARGO_REGISTRY_TOKEN }}